services:

  go-cli:
    image: golang:1.26.4-bookworm
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

volumes:
  go-mod-cache:
  go-build-cache: